version: 1

settings: # required
  course_name: go

  gitlab_base_url: https://gitlab.manytask.org
  public_repo: go/public-2025-spring
  students_group: go/students-2025-spring

ui:
  task_url_template: https://github.com/slon/shad-go/tree/main/$TASK_NAME

  # optional, any number of links
  links:
    "TG Channel": https://t.me/+eb5z6ZS-sI8xZDNi
    "TG Chat": https://t.me/+Tk8VTMAk5Tlp7Txm
    "LMS": https://lk.yandexdataschool.ru/
    "Contribute Manytask": https://github.com/manytask

deadlines:
  timezone: Europe/Moscow

  deadlines: hard # hard/interpolate
  # max_submissions: 10  # optional
  # submission_penalty: 0.1  # optional

  schedule:
    - group: Hello World
      start: 2025-02-13 18:00
      steps:
        0.3: 2025-02-23 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: sum
          score: 100
        - task: tour0
          score: 100
        - task: wordcount
          score: 100
        - task: urlfetch
          score: 100
        - task: fetchall
          score: 100

    - group: Basics
      start: 2025-02-20 18:00
      steps:
        0.3: 2025-03-02 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: hotelbusiness
          score: 100
        - task: hogwarts
          score: 100
        - task: utf8
          score: 100
        - task: varfmt
          score: 100
        - task: speller
          score: 100
        - task: forth
          score: 100

    - group: Interfaces
      start: 2025-02-27 18:00
      steps:
        0.3: 2025-03-09 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: otp
          score: 100
        - task: retryupdate
          score: 100
        - task: lrucache
          score: 100
        - task: externalsort
          score: 100
        - task: ciletters
          score: 100
        - task: yamlembed
          score: 100

    - group: Goroutines
      start: 2025-03-06 18:00
      steps:
        0.3: 2025-03-16 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: tour1
          score: 100
        - task: once
          score: 100
        - task: rwmutex
          score: 100
        - task: waitgroup
          score: 100
        - task: cond
          score: 100
        - task: ratelimit
          score: 100

    - group: "[HW] Gitfame"
      start: 2025-03-06 18:00
      end: 2025-03-21 23:59
      tasks:
        - task: gitfame
          score: 0

    - group: Testing
      start: 2025-03-13 18:00
      steps:
        0.3: 2025-03-23 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: testequal
          score: 100
        - task: fileleak
          score: 100
        - task: tabletest
          score: 100
        - task: tparallel
          score: 200
        - task: iprange
          score: 100

    - group: Concurrency with shared memory
      start: 2025-03-20 18:00
      steps:
        0.3: 2025-03-31 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: dupcall
          score: 200
        - task: keylock
          score: 200
        - task: batcher
          score: 200
        - task: pubsub
          score: 300

    - group: HTTP
      start: 2025-03-27 18:00
      steps:
        0.3: 2025-04-06 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: urlshortener
          score: 100
        - task: digitalclock
          score: 100
        - task: middleware
          score: 200
        - task: firewall
          score: 200
        - task: olympics
          score: 200

    - group: Database
      start: 2025-04-03 13:00
      steps:
        0.3: 2025-04-13 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: dao
          score: 100
        - task: ledger
          score: 200
        - task: shopfront
          score: 100
        - task: rsem
          score: 300

    - group: "[HW] Dist Build"
      start: 2025-04-03 13:00
      end: 2025-05-11 23:59
      tasks:
        - task: distbuild
          score: 1

    - group: Generics
      start: 2025-04-14 18:00
      steps:
        0.3: 2025-04-27 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: genericsum
          score: 100
        - task: treeiter
          score: 100
        - task: consistenthash
          score: 200
        - task: coverme
          score: 300

    - group: Reflect
      start: 2025-04-17 18:00
      steps:
        0.3: 2025-05-04 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: reversemap
          score: 100
        - task: jsonlist
          score: 100
        - task: jsonrpc
          score: 100
        - task: excelwriter
          score: 200
        - task: structtags
          score: 100

    - group: Low level
      start: 2025-04-24 18:00
      steps:
        0.3: 2025-05-11 23:59
      end: 2025-07-10 23:59
      tasks:
        - task: illegal
          score: 100
        - task: blowfish
          score: 100
        - task: gzep
          score: 100

    # - group: Analysis
    #   start: 2024-05-11 13:00
    #   steps:
    #     0.3: 2024-05-21 23:59
    #   end: 2024-07-10 23:59
    #   tasks:
    #     - task: testifycheck
    #       score: 200

    - group: Observability
      start: 2025-05-15 13:00
      end: 2025-07-10 23:59
      tasks:
        - task: firegod
          score: 200

    - group: Bonus
      start: 2025-04-04 13:00
      end: 2025-07-10 23:59
      tasks:
        - task: smartsched
          is_bonus: true
          score: 200
          watch:
            - distbuild/pkg/scheduler
        - task: wscat
          is_bonus: true
          score: 200

        - task: gossip
          is_bonus: true
          score: 300
        - task: wasm
          is_bonus: true
          score: 300
        - task: psycher
          is_bonus: true
          score: 200

        - task: testifycheck
          is_bonus: true
          score: 200
